# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Blog
subtitle: Guoqing's Blog
description:
author: Guoqing Wang
email:
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://logtous.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:month-:day-:title.md # File name of new posts
default_layout: post
auto_spacing: false
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Server
## Hexo uses Connect as a server
## You can customize the logger format as defined in
## http://www.senchalabs.org/connect/logger.html
port: 4000
server_ip: 0.0.0.0
logger: false
logger_format:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: icarus

# Index
# https://github.com/hexojs/hexo-generator-index
index_generator:
  per_page: 5
  order_by: -date

# Archive
# https://github.com/hexojs/hexo-generator-archive
archive_generator:
  per_page: 100
  yearly: true
  monthly: true
  daily: false

# Category
# https://github.com/hexojs/hexo-generator-categorys
category_generator:
  per_page: 100

# Tag
# https://github.com/hexojs/hexo-generator-tag
tag_generator:
  per_page: 100

# Feed
# https://github.com/hexojs/hexo-generator-feed
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

# Marked
# https://github.com/hexojs/hexo-renderer-marked
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

# Deploy
# https://github.com/hexojs/hexo-deployer-git
deploy:
  type: git
  message: update
  repo:
    github: git@github.com:wonderful60/wonderful60.github.io.git,master
    coding.net: git@git.coding.net:wonderful60/MyBlog.git,master

# Sitemap
# https://github.com/hexojs/hexo-generator-sitemap
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

# Qiniu
# https://github.com/gyk001/hexo-qiniu-sync
qiniu:
  offline: false
  sync: true
  bucket: hexo-blog-picture
  access_key: CbmCUQLTad6Ds1IRhnic14YH0TRfj66WUtXsQ7Gj
  secret_key: kiAwVnmE1vgiiCpWrgm9SqzjsRuFLNJl1vdLv7EL
  dirPrefix: static
  urlPrefix: http://7xtlfa.com1.z0.glb.clouddn.com/static
  local_dir: static
  update_exist: true
  image:
    folder: images
    extend:
  js:
    folder: js
  css:
    folder: css

search:
  path: search.xml
  field: post